<?php
/**
 * Plugin Name: Auto Page Generator
 * Plugin URI: https://webdisk.info/blog
 * Description: It will create 3 pages for you like Privacy-policy, Terms & Condition & Disclaimer.
 * Author: Kali Prasad Panda
 * Author URI: https://webdisk.info
 * Version: 1.0.0
 * Text Domain: Auto-page-generator  echo ; 
*/

if(!defined('ABSPATH'))
{
    //echo "what you want to do?";
   exit;
}

define( 'APG_DIR_PATH', plugin_dir_path( __FILE__ ) );
define('APG_PLUGIN_URL', plugins_url());
define('APG_ADMIN_URL', admin_url());


function add_apg_menu() {
    add_menu_page( 'Auto-page-generator',//page-title
   'Auto Page Generator',// menu-title
   'manage_options',//capabilities (user level access) 
   'auto-page-generator',// slug
   'apg_admin_view', //call back function
   'dashicons-welcome-add-page', //icon url
    7 //position 
  );}
  add_action('admin_menu', 'add_apg_menu');





  function create_pages(){
        //create 3 pages after activation of the plugin
      $privacy_policy=array();
      $privacy_policy['post_title']="Privacy Policy";
      $privacy_policy['post_content']="This is privacy policy page which is auto generated by the auto-page-generator plugin";
      $privacy_policy['post_status']="publish";
      $privacy_policy['post_slug']="privacy-policy";
      $privacy_policy['post_type']="page";

      $tnc=array();
      $tnc['post_title']="Terms & Condition";
      $tnc['post_content']="This is Terms & Condition page which is auto generated by the auto-page-generator plugin";
      $tnc['post_status']="publish";
      $tnc['post_slug']="Terms-condition";
      $tnc['post_type']="page";

      $disclaimer=array();
      $disclaimer['post_title']="Disclaimer";
      $disclaimer['post_content']="This is Disclaimer page which is auto generated by the auto-page-generator plugin";
      $disclaimer['post_status']="publish";
      $disclaimer['post_slug']="disclaimer";
      $disclaimer['post_type']="page";

      $privacy_policy_id=wp_insert_post($privacy_policy); //function called for create pages and returned id stored in $$privacy_policy_id
      $tnc_id=wp_insert_post($tnc);
      $disclaimer_id=wp_insert_post($disclaimer);

    add_option('privacy_policy_id',$privacy_policy_id);
    add_option('tnc_id',$tnc_id);
    add_option('disclaimer_id',$disclaimer_id);

  }
  register_activation_hook(__FILE__,'create_pages');


//drop table after uninstall the plugin
  function deactivate_post_table(){
    //   global $wpdb;
    //   $wpdb->query("DROP table IF Exists");

    $get_pid=get_option('privacy_policy_id');
    $get_tid=get_option('tnc_id');
    $get_did=get_option('disclaimer_id');

    if(!empty($get_pid)){
        wp_delete_post($get_pid,true);
        delete_option('privacy_policy_id');

    }
    if(!empty($get_tid)){
        wp_delete_post($get_tid,true);
        delete_option('tnc_id');
    }
    if(!empty($get_did)){
        wp_delete_post($get_did,true);
        delete_option('disclaimer_id');
    }
  }
  register_deactivation_hook(__FILE__,'deactivate_post_table');
  register_uninstall_hook(__FILE__,'deactivate_post_table');




  function apg_admin_view(){
    include_once APG_DIR_PATH."dash.php";
  }

?>